## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SuiteSparse")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  # Deploy documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("SuiteSparse")); include(joinpath("docs", "make.jl"))'
